ports:
# Web UI (static resources)
- port: 8080
  visibility: public
  onOpen: ignore
# Celery
- port: 5555
  visibility: public
  onOpen: ignore

tasks:
- init: |
    cp variables.env_example variables.env
    docker-compose pull
    docker-compose up -d 

vscode:
  extensions:
    - ms-python.vscode-pylance
    - ms-python.python
    - redhat.vscode-yaml
    - ms-azuretools.vscode-docker
    - ms-vscode-remote.remote-containers
